# .pre-commit-config.yaml
# This configuration runs clang-format only on modified lines of C/C++/CUDA files

repos:
-   repo: local
    hooks:
    -   id: clang-format-modified-lines
        name: clang-format-modified-lines
        description: "Run clang-format only on modified lines of C/C++/CUDA files"
        entry: ./.pre-commit-clang-format.sh
        language: system
        pass_filenames: false
        always_run: true
